name: MLOps project tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest isort
        pip install -r requirements.txt
    
    - name: Sort imports with isort
      run: |
        isort .
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Run tests with Pytest
      run: |
        pytest
